language: csharp
mono: none
dotnet: 2.0.0

solution: log4net.ElasticSearch.sln

script:
 - cd src
 - dotnet restore
 - dotnet build -c Release
 - dotnet test log4net.ElasticSearch.NetCore.Tests/log4net.ElasticSearch.NetCore.Tests.csproj


deploy:
  skip_cleanup: true
  on:
      all_branches: true
  provider: script
  script: chmod +x ./scripts/nuget_publish.sh && ./scripts/nuget_publish.sh $NUGET_API_KEY $NUGET_SOURCE

