language: csharp
mono: none
dotnet: 2.0.0

solution: log4net.ElasticSearch.sln

script:
 - cd src
 - dotnet restore
 - dotnet build
 - dotnet test log4net.ElasticsSearch.NetCore.Tests/log4net.ElasticsSearch.NetCore.Tests.csproj

